services:
  gateway-server:
    build: 
      context: ./gateway-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TZ=Asia/Seoul
      - JWT_SECRET=maple_story_jwt_secret
      - AUTH_SERVER_URL=http://auth-server:3000
      - EVENT_SERVER_URL=http://event-server:3000
    depends_on:
      - auth-server
      - event-server

  auth-server:
    build:
      context: ./auth-server
    environment:
      - PORT=3000
      - TZ=Asia/Seoul
      - JWT_SECRET=maple_story_jwt_secret
      - MONGODB_URI=mongodb://mongodb:27017/auth-server
    depends_on:
      - mongodb

  event-server:
    build:
      context: ./event-server
    environment:
      - PORT=3000
      - TZ=Asia/Seoul
      - AUTH_SERVER_URL=http://auth-server:3000
      - MONGODB_URI=mongodb://mongodb:27017/event-server
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: